
import s3Banner from        '@/s3-banner.vue'
import s3Bottom from        '@/s3-bottom.vue'
import s3Card from          '@/s3-card.vue'
import s3Date from          '@/s3-date.vue'
import s3Dealer from        '@/s3-dealer.vue'
import s3FirstLogin from    '@/s3-firstlogin.vue'
import s3Formvalcode from   '@/s3-formValCode.vue'
import s3Functionpanel from '@/s3-functionPanel.vue'
import s3Input from         '@/s3-input.vue'
import s3InputNumber from   '@/s3-inputNumber.vue'
import s3Login from         '@/s3-login.vue'
import s3Search from        '@/s3-search.vue'
import s3Upload from        '@/s3-upload.vue'
